# Generated by Django 5.2.8 on 2025-11-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0002_remove_users_bio_users_email_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
    ]
