# Generated by Django 5.2.8 on 2025-11-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0003_accounts_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы'),
        ),
    ]
