# Generated by Django 5.2.8 on 2025-11-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0004_users_auth_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='erp_tools.projects', verbose_name='Проект')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='erp_tools.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Команда проекта',
                'verbose_name_plural': 'Команды проекта',
                'ordering': ['-created_at'],
            },
        ),
    ]
