# Generated by Django 5.2.8 on 2025-11-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0005_projectteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='permitted_accounts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
