# Generated by Django 5.2.8 on 2025-11-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0006_users_permitted_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteams',
            name='role',
            field=models.CharField(blank=True, choices=[('ProjectManager', 'Руководитель проекта'), ('FunctionalArchitect', 'Функциональный архитектор'), ('TechnicalArchitect', 'Технический архитектор'), ('Analyst', 'Аналитик'), ('Developer', 'Разработчик'), ('Client', 'Клиент'), ('Other', 'Прочая'), ('Tester', 'Тестировщик'), ('Clerk', 'Клерк'), ('OnlyIssues', 'Only Issues')], max_length=100, null=True, verbose_name='Роль'),
        ),
    ]
