# Generated by Django 5.2.8 on 2025-11-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0007_alter_projectteams_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='erp_tools.users', verbose_name='Manager'),
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('tax_code', models.CharField(max_length=255, verbose_name='ИНН')),
                ('code', models.CharField(max_length=255, verbose_name='Код компании')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_expired', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='erp_tools.users', verbose_name='Заявитель')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='erp_tools.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='DataBases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('path', models.CharField(max_length=255, verbose_name='Путь')),
                ('server', models.CharField(max_length=255, verbose_name='Сервер')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_bases', to='erp_tools.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'База данных',
                'verbose_name_plural': 'Базы данных',
                'ordering': ['-date_create'],
            },
        ),
    ]
