# Generated by Django 5.2.8 on 2025-11-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0008_projects_manager_companies_databases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_check', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Время проверки')),
                ('time_dead_line', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Время дедлайна')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('to_do_task', models.TextField(blank=True, null=True, verbose_name='Запросить данные')),
                ('create_sd_issue', models.BooleanField(default=False, verbose_name='Создание SD Issue')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_expired', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_as_applicant', to='erp_tools.users', verbose_name='Заявитель')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='erp_tools.companies', verbose_name='Компания')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_as_supervisor', to='erp_tools.users', verbose_name='Контролер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_as_responsible', to='erp_tools.users', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-date_create'],
            },
        ),
    ]
