# Generated by Django 5.2.8 on 2025-11-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0010_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_as_supervisor', to='erp_tools.users', verbose_name='Супервайзер'),
        ),
    ]
