# Generated by Django 5.2.8 on 2025-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0013_alter_issues_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('waiting', 'Ожидает'), ('testing', 'Тестирование'), ('done', 'Выполнена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
