# Generated by Django 5.2.8 on 2025-11-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0014_alter_issues_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='date_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='issues',
            name='date_end_plan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания планирования'),
        ),
        migrations.AddField(
            model_name='issues',
            name='date_start_plan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала планирования'),
        ),
        migrations.AddField(
            model_name='issues',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='issues',
            name='sla_check',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='СЛА проверки'),
        ),
        migrations.AddField(
            model_name='issues',
            name='sla_deadline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='СЛА дедлайна'),
        ),
        migrations.AddField(
            model_name='issues',
            name='sla_exec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='СЛА выполнения'),
        ),
        migrations.AddField(
            model_name='issues',
            name='sla_reac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='СЛА реакции'),
        ),
        migrations.AddField(
            model_name='issues',
            name='time_check',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Время проверки'),
        ),
        migrations.AddField(
            model_name='issues',
            name='time_dead_line',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Время дедлайна'),
        ),
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название спринта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='erp_tools.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринты',
                'ordering': ['-date_create'],
            },
        ),
        migrations.AddField(
            model_name='issues',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='erp_tools.sprints', verbose_name='Спринт'),
        ),
    ]
