# Generated by Django 5.2.8 on 2025-11-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0015_issues_date_check_issues_date_end_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('role', models.CharField(blank=True, choices=[('ProjectManager', 'Руководитель проекта'), ('FunctionalArchitect', 'Функциональный архитектор'), ('TechnicalArchitect', 'Технический архитектор'), ('Analyst', 'Аналитик'), ('Developer', 'Разработчик'), ('Client', 'Клиент'), ('Other', 'Прочая')], max_length=100, null=True, verbose_name='Роль')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_teams', to='erp_tools.companies', verbose_name='Компания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_team_responsible', to='erp_tools.users', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Рабочая группа клиента',
                'verbose_name_plural': 'Рабочие группы клиента',
                'ordering': ['-date_create'],
            },
        ),
    ]
