# Generated by Django 5.2.8 on 2025-11-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0016_clientteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='applicant_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_as_applicant', to='erp_tools.clientteams', verbose_name='Заявитель (клиент)'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_as_applicant', to='erp_tools.users', verbose_name='Заявитель (пользователь)'),
        ),
    ]
