# Generated by Django 5.2.8 on 2025-11-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('erp_tools', '0017_issues_applicant_client_alter_issues_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='applicant_client',
        ),
        migrations.AddField(
            model_name='issues',
            name='applicant_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['users', 'clientteams']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='issues',
            name='applicant_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
