# Generated by Django 5.2.8 on 2025-12-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0018_change_applicant_to_generic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='applicant_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['users', 'clientteams']}, null=True, on_delete=models.CASCADE, to='contenttypes.contenttype'),
        ),
        # Поле external_id уже существует в базе данных, поэтому пропускаем его добавление
        # migrations.AddField(
        #     model_name='users',
        #     name='external_id',
        #     field=models.CharField(blank=True, db_index=True, help_text='Уникальный буквенно-цифровой идентификатор для внешних систем', max_length=32, null=True, unique=True, verbose_name='Внешний идентификатор'),
        # ),
    ]
