# Generated by Django 5.2.8 on 2026-02-13 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_tools', '0021_rename_issue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientteams',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_teams', to='erp_tools.projects', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='users',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный буквенно-цифровой идентификатор для внешних систем', max_length=32, null=True, unique=True, verbose_name='Внешний идентификатор'),
        ),
    ]
